services/discourse_translator/google.rb

Hi,
I added three entries to `google.rb` `SUPPORTED_LANG`. The first was new norwegian locale mapping `nb_NO => 'no'`. The `SUPPORTED_LANG` already had entry for norwegian, but it was `no_NO => 'no'`. If I understand correctly, that locale is deprecated and discourse uses the new `nb_NO` locale.
The two other entries in `SUPPORTED_LANG` are estonian and latvian locale mappings. Google translate API seems to support both of those languages but the mappings were missing from `google.rb`.

Add norwegian, estonian and latvian language support to google backend

---

spec/models/post_spec.rb

An easy fix to remove the warning in Rails 6.0.0

FIX: Remove update_attributes! which is deprecated in Rails 6.0.0

---

plugin.rb

Zeitwerk is failing when we are searching for Jobs::Onceoff and Jobs::Base without going back to the top-level namespace (this is correlated to the fact that we got Onceoff base class and module with the same name). 
I noticed that in plugins we are using sometimes :: and sometimes not and that gives me comfort that this change will not break anything.
Travis error: https://travis-ci.org/discourse/discourse/jobs/585072364

FIX: Use top-level namespace for base classes

---

services/discourse_translator/microsoft.rb

https://docs.microsoft.com/en-us/azure/cognitive-services/translator/request-limits
related to https://meta.discourse.org/t/translate-button-unable-to-translate-one-post-popup-error-the-field-text-must-be-a-string-or-array-type-with-a-maximum-length-of-5000/132083/10

FIX: Microsoft translator limit is 5000 characters

---

config/locales/server.en.yml
config/locales/server.es.yml
config/settings.yml
plugin.rb
services/discourse_translator/yandex.rb
spec/services/yandex_spec.rb

This PR adds Yandex as translation processor, which is free

Add Yandex Translator

---

config/locales/server.en.yml
config/settings.yml
services/discourse_translator/microsoft.rb
spec/services/microsoft_spec.rb

As per https://docs.microsoft.com/en-us/azure/cognitive-services/translator/reference/v3-0-reference#authenticating-with-a-multi-service-resource when a multi-service secret key is used, we have to retrieve the access_token from a different endpoint 
> Regional or Multi-Service | https://<your-region>.api.cognitive.microsoft.com/sts/v1.0/issueToken
This PR provides a site setting for the user to select the region of their azure subscription key.

FEATURE: Add support for Cognitive Service’s multi-service resource.

---

services/discourse_translator/google.rb
services/discourse_translator/microsoft.rb
spec/services/google_spec.rb

The docs now recommends `POST`: `POST https://translation.googleapis.com/language/translate/v2/detect`
This fixes the error message we were seeing in production: `Your client has issued a malformed or illegal request.`

FIX: POST instead of GET when interacting with google translation api.

---

db/post_migrate/20210429154318_remove_empty_translation_custom_fields.rb

Allows migrations to work with older versions of Discourse, pre 6.1 bump

DEV: un-bump migration versions

---

plugin.rb

The constants are already autoloaded by the time the plugin initializer
is called. Also `remove_dependency` is an obsolete method and shouldn't
be called manually when using Zeitwerk as the autoloader.

DEV: Remove use of `remove_dependency`.

---

services/discourse_translator/microsoft.rb

I was looking at #26 and the source for the 5000 character limit mentioned in that PR (https://docs.microsoft.com/en-us/azure/cognitive-services/translator/request-limits) now lists 10000 characters for `translate` and 50000 for `detect`.

Microsoft translator character limit is (now) 10000 characters

---

services/discourse_translator/microsoft.rb

The 10,000 limit was increased in May 2022 to 50,000 characters. Reference: https://github.com/MicrosoftDocs/azure-docs/pull/92561
Signed-off-by: Grant Slater <github@firefishy.com>

FIX: Increase Microsoft max character limit to new limit

---

config/locales/server.en.yml
config/settings.yml
services/discourse_translator/microsoft.rb
spec/services/microsoft_spec.rb

Currently, we call the translator service via the standard global and regional endpoints using token based authentication. This fails when a Virtual Network/Firewall is enabled.
Once enabled, calls must be made to a custom endpoint using a subscription key based authentication strategy.
This change adds support for custom endpoints and moves to a subscription key based authentication strategy for all endpoint types.

FEATURE: Support custom endpoints for Microsoft provider

---

services/discourse_translator/microsoft.rb

It should help with Serbian Cyrillic translation working, see https://community.openstreetmap.org/t/serbian-cyrillic-is-not-being-translated/9115 for original report - i.e. it fails with _"An error occurred: The translator is unable to translate this language."_ even if https://www.bing.com/translator has no problem with translating it manually.

FIX: typo for Serbian Cyrillic breaks its translation

---

lib/discourse_translator/guardian_extension.rb
spec/lib/guardian_extension_spec.rb
spec/serializers/post_serializer_spec.rb

Fix for [500 error - NoMethodError (undefined method `groups’ for nil:NilClass)](https://meta.discourse.org/t/oops-500-error-nomethoderror-undefined-method-groups-for-nil-nilclass/265062). It was happening when trying to visit a post while there was no user logged in and the plugin is enabled.

FIX: Fix for anon users visiting posts when the plugin is enabled

---

config/locales/server.en.yml
config/settings.yml
lib/discourse_translator/guardian_extension.rb
plugin.rb
spec/controllers/translator_controller_spec.rb
spec/lib/guardian_extension_spec.rb
spec/serializers/post_serializer_spec.rb

**Context**
The customer wants to limit post translation to only allowing the translation of posts created by users in picked groups. This will only allow the translation of topics deemed important by the customer.
**End Result**
Implemented a `SiteSetting` to control which groups can create posts that will be cleared for translation. Leaving the list empty will allow the translation for posts made by any group.

FEATURE: Restrict translations by poster group

---

services/discourse_translator/microsoft.rb

Serbian is a digraphic language with both the Latin and Cyrillic forms are common and seemingly used interchangeably.
Discourse's Serbian translation uses both Latin (widely) and Cyrillic (mostly limited to dates etc).
Without this workaround when the Microsoft Translate API detects `sr-Latn` the `raise TranslatorError.new(I18n.t("translator.failed"))` is thrown because `sr-Latn` is not matched. This adds an inelegant  workaround by adding `sr-Latn` to supported list. `sr-Latn` isn't directly a supported Discourse i18n.

FIX: Serbian is digraphic while Microsoft API treats as separate languages

---

spec/serializers/post_serializer_spec.rb

The `#queue_jobs=` method on site settings has been [deprecated](https://github.com/discourse/discourse/commit/1b65469b64e9e569fed67ae11f1dd9ee37702f5c) and replaced by `Jobs.run_later!` and `Jobs.run_immediately!`. This PR replaces usages in this plugin so we can remove the fallback in core.
The fallback used in core for reference:
https://github.com/discourse/discourse/blob/main/app/models/site_setting.rb#L109-L115

DEV: Replace deprecated queue_jobs site setting in tests

---

config/locales/client.en.yml
config/settings.yml

This is so the plugins settings are better categorized in the site settings UI.

DEV: Change settings root from plugins: to discourse_translator

---

services/discourse_translator/amazon.rb
spec/services/amazon_spec.rb

We're currently seeing the following exception in production logs:
```
Job exception: text size cannot be zero
```
which is happening when we try to detect language of a blank string.
This change fixes that by returning `nil` instead of issuing a request when that happens.

FIX: Don't attempt to detect language of blank strings

---

services/discourse_translator/libretranslate.rb
spec/services/libretranslate_spec.rb

Fixes an issue with 86dd9ce8a945def3d4581dbc4eac0d971adcce90, I merged a bad commit. This also adds some basic tests (that would have caught my bad commit).

FIX: Broken LibreTranslate support

---

assets/javascripts/discourse/initializers/extend-for-translate-button.js
assets/stylesheets/common/post.scss
config/settings.yml
plugin.rb
services/discourse_translator/amazon.rb
services/discourse_translator/base.rb
services/discourse_translator/google.rb
services/discourse_translator/libretranslate.rb
services/discourse_translator/microsoft.rb
services/discourse_translator/yandex.rb
spec/controllers/translator_controller_spec.rb
spec/models/topic_spec.rb

Currently, only posts are being translated. When a post is the first post, we should include information about the topic.
Meta https://meta.discourse.org/t/feature-request-topic-title-translation/144714
Demo

FEATURE: translate topic

---

spec/controllers/translator_controller_spec.rb

The current test setup creates the admin with the same user ID every time, causing a unique index violation on the admin group membership, blocking https://github.com/discourse/discourse/pull/25435.
This PR changes the current approach to a more standard `fabricate → sign in` approach.

DEV: Make admin login work with new TL4 admins

---

services/discourse_translator/amazon.rb
services/discourse_translator/base.rb
spec/services/amazon_spec.rb

The Amazon translate API allows for a text to be up to 10k bytes.
This changes the `MAXLENGTH` constant into the `MAX_BYTES` and uses a `truncate` method that works at the bytes level instead of the character/grapheme level.
Ref - https://meta.discourse.org/t/increase-amazon-translate-limit-to-10-000-characters/304579

FIX: Amazon text size is 10k bytes

---

lib/discourse_translator/guardian_extension.rb
plugin.rb
spec/controllers/translator_controller_spec.rb
spec/lib/guardian_extension_spec.rb

While making some updates to the translator plugin, I found some generic guardian additions which could potentially cause conflicts. e.g. `guardian.user_group_allowed?` -> `guardian.user_group_allow_translate?`.
This PR 
- makes the guardian functions scoped to translate
- for the two methods above(^), uses the available `SiteSetting.group_map` functions and `user.in_any_groups` functions
- removes some shared examples 🙈 to make reading tests easier
- moves old code to `add_to_serializer`

DEV: Scope guardian methods to the plugin and some cleanup

---

plugin.rb
spec/jobs/detect_translation_spec.rb
spec/serializers/post_serializer_spec.rb

Each time a post is getting serialized, we check if the post's language has already been detected or not. If it has, there are no real side effects, and if it hasn't, the plugin sends a request to the enabled translator to detect the post's language.
The problem happens when we have small actions posts with no raw and the job keeps getting queued endlessly. I considered adding some checks at Jobs::DetectTranslation, or `cluster_concurrency 1`, so it doesn't re-trigger in the event some actions happen too quickly, but it might seem unnecessary. We'll see.
This PR prevents us from sending the post for language detection.
(There will be another PR to handle Amazon's errors due to misconfiguration)

FIX: Skip translations for empty or small actions posts

---

config/locales/server.en.yml
plugin.rb
services/discourse_translator/amazon.rb
spec/jobs/detect_translation_spec.rb

In the `Job::DetectTranslation`, sometimes missing "detection" can lead to the post getting published again despite there being no changes. This then causes the post to re-serialize, and enqueue `Job::DetectTranslation` again. 🔥 
This PR ensures that post publishing only happens if there was a change in the custom fields.

FIX: Avoid publishing post when there is no change

---

lib/discourse_translator/guardian_extension.rb
spec/lib/guardian_extension_spec.rb

The `GuardianExtension#poster_group_allow_translate?` method restricts and determines whether a post can be translated based on the poster's group membership. There are reports that this errors out when deleting spammers.
The problem is that when a spammer is deleted, their post `user_id` is nullified, and because the above method doesn't account for this case, we try to call `#in_any_groups?` on `nil`, which errors out.
This PR fixes that by explicitly accounting for the case of a post with a `nil` user ID.
---
We have to make a decision here, since we're losing the history of which groups the poster was in, whether the post should be translatable or not. I'm defaulting to `false` here. It should be a minor thing as deleting a spam user should hide or delete their post as well.

FIX: Don't error out on deleted users

---

services/discourse_translator/google.rb

No globe appears on non-English posts on my forum and the error in production.log is ```Job exception: Requests from referer <empty> are blocked.```
The working fix is from /u/arkshine on the forum, see https://meta.discourse.org/t/why-is-there-no-earth-icon-after-i-configured-the-google-translator-api/280405

Send referer header to google.

---

spec/services/google_spec.rb

I suspect the spec was passing before due to a regression in mocha which has been fixed: https://github.com/freerange/mocha/commit/3b60b7df390bce19b928099281c9af8bccbe8472
Not 100% sure, but the criticality of the fix in a spec doesn’t seem to necessitate more investigation.

DEV: fix spec for mocha 2.4.1

---

app/services/problem_check/microsoft_azure_key.rb
config/locales/server.en.yml
plugin.rb
spec/services/problem_check/microsoft_azure_key_spec.rb

Added a Problem checker with a "high" priority for the Azure key, so sit administrators can see the problem of missing Azure key on the dashboard in real time when the translator is configured as Microsoft.

FEATURE: Add Azure key ProblemChecker

---

plugin.rb
services/discourse_translator/microsoft.rb
spec/services/microsoft_spec.rb

In the previous commit (95e2043) we used ProblemCheck to alert the administrator of the problem of missing Microsoft Azure Key. Therefore, it is no longer necessary to log the error about missing Azure Key. This commit adds a rescue for this error to remove it from the log.

DEV: Do not log Job Exception: No Azure Key

---

app/services/problem_check/translator_error.rb
config/locales/server.en.yml
plugin.rb
services/discourse_translator/base.rb
services/discourse_translator/microsoft.rb
spec/services/microsoft_spec.rb

What does it add?
=================
This commit brings error messages from Microsoft Translator to the
administrator dashboard.
Specifically, a new InlineProblemCheck has been added, which reports the
error information in a human-readable way on the administrator dashboard
every time the translator server reports an error. When the translation
is successful, the error is considered to have been fixed and removed
from the dashboard.
ref: /t/134047
Screenshot
=========

FEATURE: Add translator error ProblemCheck for Microsoft 

---

services/discourse_translator/google.rb
spec/services/google_spec.rb

see comment for rationale here - but google chokes on en=>en translations and they are an inevitable effect of how our UI presents the translate feature. this happens any time a topic title is in the same language as the user's.
this fixes that by updating the google service to pass through same-language translation requests.

Handle same language translations

---

.discourse-compatibility

https://github.com/discourse/discourse-translator/pull/210 set the commit hash to a commit from core, but it should have been set to a commit in discourse-translator before the breaking change was introduced. In this case, that's 7d411e458bdd449f8aead2bc07cedeb00b856798.

FIX: Entry in .discourse-compatibility was wrong

---

app/jobs/scheduled/automatic_translation_backfill.rb
config/settings.yml
spec/jobs/automatic_translation_backfill_spec.rb

- **DEV: Remove manual lock in favor of cluster_concurrency**
- **FEATURE: Add hidden settings to limit automatic translation scope**

FEATURE: Add hidden settings to limit automatic translation scope

---

lib/discourse_translator/automatic_translations.rb

Also makes reactive translation respect limiting translation to public content setting

DEV: Disable automatic translation via reactive events when automatic rate is zero

---

app/services/discourse_translator/discourse_ai.rb
lib/discourse_translator/content_splitter.rb
spec/lib/content_splitter_spec.rb
spec/services/discourse_ai_spec.rb

Requires: https://github.com/discourse/discourse-translator/pull/248
We are seeing a lot of 
```
Failed to machine-translate Post#1708161 to it: <html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
```
Timeouts may happen when we send large chunks over to our LLM for translation. Timeouts may also happen in two ways:
1. Site user presses 🌐 to translate a post manually (controller API); or
2. We send old posts for backfilling (job).
This PR solves (2). (1) will be handled in a different PR. We will loosely split content up into chunks. Example post raw is meta's /t/354449.

FIX: Split content for translation before sending

---

assets/stylesheets/common/common.scss

Should resolve this issue with the enormous button in some cases 
After:

UX: fix scaling of translator button in topic-progress bar

---

spec/system/anon_language_switcher_spec.rb

Clicking on the switcher is already causing a navigation to the topic to refresh content. In this spec we were doing a `visit_topic` right after which could be working in selenium, but will often fail on playwright with the following error:
```ruby
Playwright::Error:
net::ERR_ABORTED at http://localhost:31339/t/life-strategies-from-the-art-of-war/96
Call log:
- navigating to "http://localhost:31339/t/life-strategies-from-the-art-of-war/96", waiting until "load"
```

DEV: prevents double navigation

---

app/services/discourse_ai/base_translator.rb
app/services/discourse_ai/language_detector.rb
spec/services/discourse_ai/base_translator_spec.rb
spec/services/discourse_ai/language_detector_spec.rb
spec/services/discourse_ai_spec.rb

FIX: Switch to DiscourseAi's StructuredOutput
